channels:
- conda-forge
dependencies:
- python=3.10.9
- pip<=22.3.1
- pip:
  - mlflow==2.4
  - cloudpickle==2.2.1
  - numpy==1.25.0
  - packaging==23.1
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
